services:
  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
    ports:
      - '3666:3306'
  server:
    container_name: server
    image: node:16
    environment:
      - DEBUG=app:*
    ports:
      - '3333:3000'
    volumes:
      - ./server/src:/app
    working_dir: /app
    command: sh -c 'yarn start'
  client:
    container_name: client
    image: node:16
    environment:
      - PORT=8000
    tty: true
    ports:
      - '8888:8000'
    volumes:
      - ./client/src:/app
    working_dir: /app
    command: sh -c 'yarn start'
